version: "3.9"
services:
  user_service:
    build: ./user_service
    ports:
      - "5001:5001"

  product_service:
    build: ./product_service
    ports:
      - "5002:5002"
    depends_on:
      - rabbitmq

  order_service:
    build: ./order_service
    ports:
      - "5003:5003"
    depends_on:
      - user_service
      - product_service
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
